### ISSUE TITLE
Can't play video or stream, a lot of command without output + no docs

### ISSUE THREAD

**Issue by Timoti11** [Xxathyx/MediaPlayer#1]
Hi! I wanna test it for my server, but no commands besided /videos download and /screen get and render don't work...
I need: 1.20.1 plugin with video from local files of my dedictated server for cinema online)

**Comment by Xxathyx** [comment]
Hello, thanks for your interest.

The plugin has a few problems and therefore, is not entirely finished and some error connection messages can appear on the console other features are still in development, such as audio, since the plugin isn't released, global documentation lack, and that's true.

However, the latest plugin version should work. I updated it last week for 1.20, here are some instructions on how to play a local video :

0. Make sure to have ffmpeg and ffprobe libraries in the libraries folder inside the plugin folder, if not you can manually download them from if your server is running under linux : [https://www.dropbox.com/s/7j5i6n9d373t515/ffmpeg?dl=0](url) and [https://www.dropbox.com/s/sw6sponbyea866u/ffprobe?dl=0](url) those are libraries used to extract frames from videos,
if you are on a dedicated server make sure that you granted permission for execution to ffprobe and ffmpeg otherwise the plugin will simply not work, and you will get a error=13.
2. If you have a video file, make sure the video format is compatible, here are the compatible formats : mp4, mov, m4v, avi, webm, mkv, gif, m3u8, ts, wmv
3. Drag your video into the videos folder, in the plugin folder.
4. Type the command /videos reload.
5. Then type /video load  (the video should not include space, otherwise you have to get the video index)
6. If the video loading is unsuccessful, you can try again, when its done you type /video play 
7. Then click on the chat-message that says create a screen.
8. Right click on the top right corner of the screen, the screen display should change into the video thumbnail.
9. Then type /video start
10. To stop it : /video stop

**Comment by Xxathyx** [comment]
I have update the plugin jar to add these features, you will have to delete the older plugin folder
